//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spruce.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SpruceEntities : DbContext
    {
        public SpruceEntities()
            : base("name=SpruceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminLog> AdminLogs { get; set; }
        public virtual DbSet<Cart> Carts { get; set; }
        public virtual DbSet<ContactU> ContactUs { get; set; }
        public virtual DbSet<CustomDesign> CustomDesigns { get; set; }
        public virtual DbSet<CustomOrder> CustomOrders { get; set; }
        public virtual DbSet<Featured> Featureds { get; set; }
        public virtual DbSet<FeedBack> FeedBacks { get; set; }
        public virtual DbSet<MadeToMeasure> MadeToMeasures { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Password> Passwords { get; set; }
        public virtual DbSet<Pix_us_ExceptionHandeling> Pix_us_ExceptionHandeling { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }
        public virtual DbSet<Subscription> Subscriptions { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Product> Products { get; set; }
    }
}
